import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import GlobalProvider from '@/providers/global-provider';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Baca Kita!',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={clsx(inter.className)}>
				<GlobalProvider>
					<section className='container pt-14'>{children}</section>
				</GlobalProvider>
			</body>
		</html>
	);
}
